baseURL = "https://brekkywrap.com/"
languageCode = "en-us"
languageLang = "en"
title = "Brekky Wrap"
disableKinds = ["taxonomyTerm"]
[menu]
[[menu.main]]
  identifier = 'archive'
  name = 'Previous issues'
  title = 'View previous issues'
  url = '/archive/'
  weight = 1
[params]
  Description = "An easily digestible summary of the latest market, economic, political and tech news from Australia and beyond. Delivered daily, Monday to Friday, for free."
  timeZone = "Australia/Perth"
  localTime = true
[permalinks]
  newsletter = '/:year/:title/'
[taxonomies]
  author = "authors"
[outputs]
  page = ['HTML', 'RSS', 'HTMLemail']
[outputFormats]
  [outputFormats.HTMLemail]
    name = 'HTMLemail'
    isHTML = true
    mediaType = 'text/html'
    path = 'email'
[markup.goldmark.renderer]
unsafe= true