baseURL = "/"
languageCode = "en-us"
languageLang = "en"
title = "Brekky Wrap"
disableKinds = ["taxonomyTerm"]
[menu]
[[menu.main]]
  identifier = 'faq'
  name = 'FAQ'
  title = 'Frequently Asked Questions'
  url = '/faq/'
  weight = 1
[[menu.main]]
  identifier = 'archive'
  name = 'Previous issues'
  title = 'View previous issues'
  url = '/archive/'
  weight = 2
[[menu.main]]
  identifier = 'rewards'
  name = 'Get free stuff 🎉'
  title = 'Refer a friend for rewards'
  url = '/rewards/'
  weight = 3
[params]
  Description = "An easily digestible summary of the latest market, economic, political and tech news from Australia and beyond. Delivered daily, Monday to Friday, for free."
[permalinks]
  newsletter = '/:year/:title/'
[taxonomies]
  author = "authors"
[outputs]
  page = ['HTML', 'RSS', 'HTMLemail']
[outputFormats]
  [outputFormats.HTMLemail]
    name = 'HTMLemail'
    isHTML = true
    mediaType = 'text/html'
    path = 'email'